version: '3'
services:
  movies:
    image: vishnuvardhanyadhav/moviesrepopaytm:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: vishnuvardhanyadhav/trainrepopaytm:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: vishnuvardhanyadhav/dthrepopaytm:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: vishnuvardhanyadhav/rechargerepopaytm:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
